### ISSUE TITLE
Undefined Variable: wphead_cb, adminhead_cb and adminpreview_cb

### ISSUE THREAD

**Issue by mimdudin** [html5blank/html5blank#180] opened 2017-11-09 01:14 UTC
hello
when I want to use custom backgrounds & custom headers, when I delete the uncomment in the following line. I encountered an error notification when running it. how to fix it?

![ab](https://user-images.githubusercontent.com/29745799/32583414-0d0253dc-c526-11e7-8cc9-2833de2711f9.png)

**Comment by deviodigital** [comment] 2017-11-11 00:44
I'll be checking into this over the next day or so. I believe I know what the issue is, but would like to double check first.

**Comment by deviodigital** [comment] 2017-11-19 01:14
So, it looks like those variables ($wphead_cb, $adminhead_cb, $adminpreview_cb) are only there as placeholders for you to use (if needed), so until you define what each of those variables do, they're going to bring back the notices you've received.

You can remove the variables from the args, so those lines in the `functions.php` file will look more like this:

`'wp-head-callback'       => '',
 'admin-head-callback'    => '',
 'admin-preview-callback' => ''`

According to [this link](https://wordpress.stackexchange.com/questions/150090/adding-theme-support-for-a-custom-header-image), you can use these to add custom actions that fire off into `wp_head` and `admin_head` respectively.

> That is the feature given by WP for us to extend to our imagination. Lets say, we want to animate or ease the image on hover of header image, then those scripts could be placed in the callback function. Just my poor imagination. :D 

Going to close this out, but feel free to open up another issue if you run into any other questions!

**Closed by deviodigital** 2017-11-19 01:14 UTC
